[manager]
ratio = [0, 4, 3]
show_symlink = false

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[plugin.prepend_previewers]]
name = "*.md"
run = "glow"
